FROM python:3.11-slim

WORKDIR /app

# Paquetes útiles para healthchecks/debug
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

EXPOSE 5001

# Flask dev server para arrancar rápido; después lo pasamos a gunicorn si querés
CMD ["python", "app.py"]
